/** Condições de venda do PDF de pedido (texto jurídico fixo). */
export const PEDIDO_CONDICOES_VENDA = [
  'O presente pedido está sujeito à aceitação da vendedora e, uma vez aceito, somente poderá ser cancelado com anuência desta.',
  'Se, a qualquer tempo, o crédito do comprador for julgado insuficiente à cobertura do pedido e não forem colocados os instrumentos usuais de garantia à disposição da vendedora, esta poderá cancelar imediatamente o pedido ou entregar tão somente a parte das mercadorias cobertas pela suficiência de crédito, independente de prévia comunicação ou fase em que se encontrar a entrega, sendo que o fato de já haver sido entregue parte das mercadorias não constituirá formação de direito para o comprador ou obrigação para a vendedora de entrega do saldo.',
  'A aprovação dos pedidos de pessoas jurídicas fica condicionada à garantia do aval de seus proprietários, sócios ou diretores. Para aprovação de pedidos de pessoas em condomínio, é necessário o aval de todos os condôminos. Sem prejuízo do dispositivo, para qualquer caso, a vendedora poderá exigir outras garantias adicionais.',
  'Para efeitos do disposto na legislação em vigor, declara o comprador que os defensivos, sementes e/ou outros insumos em fase de aquisição, se destina(m) à aplicação exclusiva nas atividades agropecuárias.',
  'Será de responsabilidade do comprador qualquer modificação na incidência fiscal e/ou instituição de tributo que afete, direta ou indiretamente, a operação descrita neste pedido.',
  'As mercadorias não retiradas dentro do prazo fixado no pedido poderão ser despachadas pela vendedora diretamente para o endereço indicado pelo comprador, correndo por conta deste as respectivas despesas de despacho, bem como estarão condicionadas aos preços e condições do dia; ou a critério a vendedora poderá o pedido ser cancelado.',
  'As mercadorias serão embarcadas em perfeitas condições, não se responsabilizando a vendedora pelo seu mau uso ou emprego indevido.',
  'A existência de financiamento bancário não exime o comprador da responsabilidade de pagamento do preço mediante recursos próprios, de aceitar as duplicatas que se originarem deste pedido e de fornecer as garantias necessárias ao crédito, quando solicitadas pela vendedora. A vendedora reserva-se o direito de sustar a entrega das mercadorias até a comprovação da liberação, a seu favor, da verba do referido financiamento.',
  'Qualquer concessão feita pela vendedora em contrário a estas condições de venda será considerada como caso isolado, que não implicará em formação de direito a favor do comprador ou de terceiros.',
  'As partes convencionam que o valor da(s) duplicata(s), emitida(s) por sua força desta compra e venda se não paga(s) em seu vencimento, será cobrado uma multa de 2% e será acrescido de taxas de juros que for praticadas na ocasião, pelo sistema bancário e financeiro. Na eventualidade de cobrança judicial, o devedor pagará os valores acima referidos, e honorários advocatícios.',
  'A vendedora se reserva o direito de, a critério, efetuar o cancelamento automático do pedido após o vencimento da data de validade do mesmo ou data prevista para a retirada da mercadoria.',
  'As mercadorias viajam por conta e risco do comprador, sendo que, mesmo caso de despacho, este se obriga a recebê-las no ato da chegada, sem responsabilidade para a vendedora por eventuais extravios, trocas, danos ou armazenagem.',
  'Qualquer pagamento efetuado pelo comprador após expirar a validade do pedido, não implica na aceitação, por parte da vendedora, como quitação do pedido ou saldo do mesmo.',
]
